CREATE TABLE sqlite_sequence(name,seq);
CREATE TABLE sessions (login_token TEXT UNIQUE NOT NULL PRIMARY KEY, blog_id REFERENCES blogs (blog_id) ON DELETE CASCADE NOT NULL);
CREATE TABLE blogs (blog_id TEXT PRIMARY KEY UNIQUE NOT NULL, name TEXT UNIQUE NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT UNIQUE NOT NULL, email_public BOOLEAN NOT NULL, date_created DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP));
CREATE TABLE posts (post_id INTEGER PRIMARY KEY AUTOINCREMENT UNIQUE NOT NULL, blog_id TEXT REFERENCES blogs (blog_id) ON DELETE CASCADE NOT NULL, title TEXT NOT NULL, content TEXT NOT NULL, summary TEXT, date_created DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP));
CREATE TABLE replies (reply_id INTEGER PRIMARY KEY NOT NULL, blog_id TEXT REFERENCES blogs (blog_id) NOT NULL, post_id INTEGER REFERENCES posts (post_id) NOT NULL, reply_name TEXT NOT NULL, content TEXT NOT NULL);
