CREATE TABLE "users" (
    id TEXT PRIMARY KEY NOT NULL UNIQUE,
    username TEXT UNIQUE NOT NULL,
    password_hash TEXT NOT NULL,
    profile_picture_url TEXT,
    description TEXT,
    signature TEXT,
    created_at DATETIME DEFAULT (CURRENT_TIMESTAMP) NOT NULL
);
CREATE TABLE "posts" (id INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, topic_id TEXT REFERENCES topics (id) NOT NULL, content TEXT NOT NULL, show_signature BOOLEAN NOT NULL, deleted BOOLEAN NOT NULL DEFAULT (0), creator_id TEXT REFERENCES users (id) NOT NULL, created_at DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP));
CREATE TABLE "topics" (id TEXT PRIMARY KEY NOT NULL UNIQUE, forum_id TEXT REFERENCES forums (id) NOT NULL, name TEXT NOT NULL COLLATE NOCASE CHECK (LOWER(name) != 'new'), description TEXT NOT NULL, total_posts INTEGER NOT NULL DEFAULT (0), locked BOOLEAN NOT NULL DEFAULT (0), creator_id TEXT REFERENCES users (id) NOT NULL, updated_at DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP), created_at DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP), UNIQUE (forum_id, name));
CREATE TABLE "forums" (id TEXT PRIMARY KEY UNIQUE NOT NULL, name TEXT UNIQUE NOT NULL CHECK (LOWER(name) != 'new'), description TEXT NOT NULL, creator_id TEXT REFERENCES users (id) NOT NULL, created_at DATETIME NOT NULL DEFAULT (CURRENT_TIMESTAMP));